controllers:
    resource: ../../src/Controller/
    type: annotation

user_management_controllers:
    resource: ../../src/Modules/UserManagement/Controller/
    type: annotation

dashboard_controllers:
    resource: ../../src/Modules/Dashboard/Controller/
    type: annotation
asset_discovery:
  resource: '../../src/Modules/AssetDiscovery/Controller/'
  type: annotation

landing_and_info:
  resource: '../../src/Modules/LandingAndInfo/Controller'
  type: annotation

audit_logging_controllers:
    resource: ../../src/Modules/AuditLogging/Controller/
    type: annotation

reporting_controllers:
    resource: ../../src/Modules/Reporting/Controller/
    type: annotation
